### ISSUE TITLE
Updated to the latest and all environment are gone!

### ISSUE THREAD

**Issue by koliapp2019** [mockoon/mockoon#743]
The upgrade wiped out all my existing environments! How do I get it back?

Thanks!

**Comment by 255kb** [comment]
You should be able to reopen the environment files from where you choose to save them. 
Click the open button at the top left: 
![image](https://user-images.githubusercontent.com/7489814/176833670-89e52a7b-3cbb-4c23-bc3d-fa93dc1dff39.png)

Concerning the bug, could you please check your logs to see if there is any error message? 
To find the app logs: https://mockoon.com/docs/latest/mockoon-data-files/settings-and-logs/
Thank you

**Comment by koliapp2019** [comment]
[2022-07-01 13:35:45.943] [error] TypeError: Object has been destroyed
    at MockoonServer.<anonymous> (C:\Users\XXX\AppData\Local\Programs\mockoon\resources\app.asar\dist\app.js:1:13790)
    at MockoonServer.emit (node:events:390:28)
    at ServerResponse.<anonymous> (C:\Users\XXX\AppData\Local\Programs\mockoon\resources\app.asar\node_modules\@mockoon\commons-server\dist\cjs\libs\server\server.js:112:22)
    at ServerResponse.emit (node:events:402:35)
    at Socket.onServerResponseClose (node:_http_server:235:23)
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12)
[2022-07-01 13:35:45.947] [error] TypeError: Object has been destroyed
    at MockoonServer.<anonymous> (C:\Users\XXX\AppData\Local\Programs\mockoon\resources\app.asar\dist\app.js:1:13790)
    at MockoonServer.emit (node:events:390:28)
    at ServerResponse.<anonymous> (C:\Users\XXX\AppData\Local\Programs\mockoon\resources\app.asar\node_modules\@mockoon\commons-server\dist\cjs\libs\server\server.js:112:22)
    at ServerResponse.emit (node:events:390:28)
    at Socket.onServerResponseClose (node:_http_server:235:23)
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12)

**Comment by 255kb** [comment]
Maybe #741 is related to this issue
