### ISSUE TITLE
CLI crashes when certificate cannot be found

### ISSUE THREAD

**Issue by anhlevfx** [mockoon/mockoon#749]
**Describe the bug**

When run command `mockoon-cli start` will throw error logs

Error: Cannot read properties of undefined (reading 'on')
    at createServer (/usr/lib/node_modules/@mockoon/cli/src/libs/server.ts:146:11)
    at Object.<anonymous> (/usr/lib/node_modules/@mockoon/cli/src/libs/server-start-script.ts:11:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Object.<anonymous> (/usr/lib/node_modules/@mockoon/cli/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)

**To Reproduce**

1. Copy file data.json from local machine (macOS) created by mockoon app to server.
2. Run command line `mockoon-cli start --data ./data.json`

**Mockoon version:**

2.0.0

nodeJs 16.6.0

**OS / OS version:**

18.04.4 LTS (Bionic Beaver)

**Comment by 255kb** [comment]
Have you tried to uninstall and reinstall the NPM package?

**Comment by anhlevfx** [comment]
Thank you for your support!
